#:schema ./via.schema.json

[surplus]
"/"        = "https://surplus.joshwel.co"
repo       = "https://github.com/markjoshwel/surplus"
"/docs"       = "https://surplus.joshwel.co/"
forges     = ["https://forge.joshwel.co/mark/surplus"]
"/funding" = "https://links.joshwel.co/donate"

[colourmeok]
repo      = "https://forge.joshwel.co/mark/colourmeok"
artifacts = ["https://forge.joshwel.co/mark/colourmeok/releases/download/vrelease/ColourMeOK.zip"]

[mulipea]
"/" = "https://gist.github.com/markjoshwel/f4fca0427ef98dd4be397acd6c6086d9"

[restepper]
"/" = "https://github.com/markjoshwel/Depot/blob/main/ReStepper/restepper.py"

[sidestepper]
repo = "https://github.com/markjoshwel/SideStepper"
forges = ["https://forge.joshwel.co/mark/sidestepper"]

[sinsandvirtues]
"/" = "https://github.com/markjoshwel/Depot/tree/main/sinsandvirtues"

[irodorio4]
"/" = "https://github.com/markjoshwel/Depot/tree/main/irodorio4"

[pokkat]
repo = "https://forge.joshwel.co/mark/pokkat"

[alookingglass]
repo = "https://forge.joshwel.co/mark/sota32/"

[raiseattention]
repo = "https://github.com/markjoshwel/RaiseAttention"

[mares]
repo = "https://github.com/markjoshwel/mares"

[meadow]
repo = "https://github.com/markjoshwel/meadow"

[tomlantic]
repo = "https://github.com/markjoshwel/tomlantic"

[via]
repo = "https://github.com/markjoshwel/via"

[hounds]
repo = "https://github.com/markjoshwel/hounds"

[portfolio-eae]
"/" = "https://markjoshwel.github.io/portfolio-eae/"

[id-asg1]
"/" = "https://markjoshwel.github.io/id-asg1/"
