#:schema ./via.schema.json

[projectnamehere]  # becomes via.joshwel.co/projectnamehere
"/" = "..."

"/issues" = "..."
"/docs" = "..."
"/funding" = "..."

"/files" = "..." 
"/downloads" = "..."
artifacts = ["...", ]

"/feed" = "..."
"/latest" = "..."

# or:
# repo = "..."
# forges = ["..."]
